my:
   greeting: Hello World from config server
   list:
       value: One,Two,three, four

db:
   connection: "{connectionString:'http://configserver', userName: 'foo', password: 'pass'}"
   host: 127.0.0.0
   port: 1200

